name: Dump Info

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GCC Version
        run: gcc --version
      - name: Installed Rust Toolchains
        run: rustup show
      - name: Installed packages
        run: dpkg --list
